from flask import Flask, render_template, request, send_from_directory
import subprocess
import os

app = Flask(__name__)

# Define the folder to store generated files
GENERATED_FOLDER = "generated_files"
if not os.path.exists(GENERATED_FOLDER):
    os.makedirs(GENERATED_FOLDER)

@app.route('/')
def index():
    return render_template('form.html')  # Render the HTML form

@app.route('/submit', methods=['POST'])
def submit():
    # Capture form data
    name = request.form['name']
    address = request.form['address']
    job_title = request.form['job_title']
    needs = request.form.getlist('needs[]')
    qualifications = request.form.getlist('qualifications[]')

    # Generate LaTeX code for the resume
    latex_code = generate_latex(name, address, job_title, needs, qualifications)

    # Save the LaTeX code to a .tex file in the generated_files folder
    tex_file = os.path.join(GENERATED_FOLDER, "resume.tex")
    with open(tex_file, "w") as f:
        f.write(latex_code)

    # Use subprocess to run LaTeX (pdflatex or xelatex) and generate the PDF
    try:
        subprocess.run(['pdflatex', '-output-directory', GENERATED_FOLDER, tex_file], check=True)
    except subprocess.CalledProcessError as e:
        return f"An error occurred while generating the PDF: {e}"

    # Return the success message with a download link
    return render_template('success.html')

@app.route('/download')
def download():
    # Serve the generated PDF file for download
    pdf_path = os.path.join(GENERATED_FOLDER, "resume.pdf")
    
    # Check if the file exists
    if os.path.exists(pdf_path):
        return send_from_directory(GENERATED_FOLDER, "resume.pdf", as_attachment=True)
    else:
        return "The PDF file was not generated successfully."

def generate_latex(name, address, job_title, needs, qualifications):
    # Start the LaTeX document
    latex_code = f"""
\\documentclass[a4paper,10pt]{article}
\\usepackage[utf8]{inputenc}
\\usepackage{geometry}
\\geometry{a4paper}
\\usepackage{enumitem}

\\begin{document}
\\title{{Resume - {name}}}
\\author{{Generated by Flask}}
\\date{{\\today}}
\\maketitle

\\section*{{Job Seeker Information}}
\\textbf{{Name:}} {name} \\\\
\\textbf{{Address:}} {address} \\\\
\\textbf{{Desired Job Title:}} {job_title}

\\section*{{Objective}}
% Objective section can be filled here, if needed.

\\section*{{Skills}}
\\begin{itemize}
    \\item Strong communication skills
    \\item Experience with dynamic table forms
    \\item LaTeX formatting and document generation
\\end{itemize}

\\section*{{Needs and Qualifications}}
\\begin{itemize}
"""

    # Add Needs and Qualifications dynamically
    for need, qualification in zip(needs, qualifications):
        latex_code += f"    \\item \\textbf{{Need:}} {need} \\textbf{{Qualification:}} {qualification}\n"

    # Close the LaTeX document
    latex_code += """
\\end{itemize}

\\end{document}
"""
    return latex_code

if __name__ == '__main__':
    app.run(debug=True)
